apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: authn-console
  namespace: authn-system
spec:
  from:
    - {group: gateway.networking.k8s.io, kind: HTTPRoute, namespace: authn-admin}
  to:
    - {group: "", kind: Service, name: zitadel}
