apiVersion: v1
kind: Namespace
metadata:
  name: authn-system
  labels:
    elektro.internal/route-scope: applications
---
apiVersion: v1
kind: Namespace
metadata:
  name: authn-admin
  labels:
    elektro.internal/route-scope: administration
