apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authn-zitadel
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.zitadel.com
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authn-oauth2-proxy
  namespace: flux-system
spec:
  interval: 1h
  url: https://oauth2-proxy.github.io/manifests
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authn-openfga
  namespace: flux-system
spec:
  interval: 1h
  url: https://openfga.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authn-heimdall
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/dadrus/heimdall/chart/heimdall
  ref:
    tag: 0.16.22
