apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
configMapGenerator:
- name: authn-edge-config
  namespace: authn
  files:
  - authorizer.py
  - permissions.py
  - index.html
  - app.js
  - style.css
  - wait-config.py
