#!/usr/bin/env python3
"""Generate the routes, proxy config and OIDC callbacks from config/sites.json."""
import argparse
import json
from pathlib import Path
import re
import sys

import yaml

ROOT = Path(__file__).resolve().parents[1]


def generate():
    sites = json.loads((ROOT / "config/sites.json").read_text())
    assert len({s["host"] for s in sites}) == len(sites), "Duplicate hostname"
    for site in sites:
        assert re.fullmatch(r"[a-z][a-z0-9-]*", site["name"])
        suffix = "${ADMIN_DOMAIN}" if site["scope"] == "administration" else "${DOMAIN}"
        assert site["scope"] in ("applications", "administration")
        assert site["host"] == site["name"] + "." + suffix or re.fullmatch(
            r"[a-z0-9-]+\." + re.escape(suffix), site["host"])
        assert re.fullmatch(r"[a-z0-9.-]+\.svc\.cluster\.local:[0-9]+", site["upstream"])

    nginx = '''# Generated by scripts/generate.py. No credentials are stored here.
worker_processes auto;
pid /tmp/nginx.pid;
error_log /dev/stderr warn;
events { worker_connections 1024; }
http {
  access_log off;
  server_tokens off;
  client_body_temp_path /tmp/client;
  proxy_temp_path /tmp/proxy;
  fastcgi_temp_path /tmp/fastcgi;
  uwsgi_temp_path /tmp/uwsgi;
  scgi_temp_path /tmp/scgi;
  resolver ${CLUSTER_DNS_IP} valid=30s ipv6=off;
  map $http_upgrade $connection_upgrade { default upgrade; '' close; }
  map "$http_x_cluster_token$http_authorization" $machine_request { '' 0; default 1; }
  server {
    listen 8080 default_server;
    server_name _;
    location = /healthz { return 200 'ok'; }
    location / { return 404; }
  }
  server {
    listen 8080;
    server_name auth.${DOMAIN};
    # Login, OIDC and user self-service must work before a site grant exists.
    location ^~ /if/admin { return 404; }
    location / {
      set $idp http://authentik-server.authn.svc.cluster.local:80;
      proxy_pass $idp;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Forwarded-Port 443;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_http_version 1.1;
    }
  }
'''
    routes = []
    all_routes = [{"name": "authentik-login", "host": "auth.${DOMAIN}", "scope": "applications"}] + sites
    for site in all_routes:
        admin = site["scope"] == "administration"
        routes.append({"apiVersion": "gateway.networking.k8s.io/v1", "kind": "HTTPRoute",
                       "metadata": {"name": site["name"], "namespace": "authn-admin" if admin else "authn"},
                       "spec": {"parentRefs": [{"name": "internal", "namespace": "gateway-system",
                                                "sectionName": "admin-https" if admin else "apps-https"}],
                                "hostnames": [site["host"]], "rules": [{"backendRefs": [
                                    {"name": "authn-edge", "namespace": "authn", "port": 80}]}]}})
    for site in sites:
        auth_header = "$http_authorization" if site.get("native_authorization") else '""'
        nginx += '''  server {
    listen 8080;
    server_name HOST;
    client_max_body_size 0;
    location ^~ /oauth2/ {
      proxy_pass http://127.0.0.1:4180;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Auth-Request-Redirect https://$host/;
      proxy_set_header Authorization "";
      proxy_set_header X-Cluster-Token "";
    }
    location = /authn/identity {
      proxy_pass http://127.0.0.1:9080/identity;
      proxy_set_header X-Original-Host $host;
      proxy_intercept_errors on;
      error_page 401 = @identity_login;
    }
    location @identity_login {
      if ($machine_request) { return 401; }
      return 302 https://$host/oauth2/start?rd=/authn/identity;
    }
    location = /_authn_check {
      internal;
      proxy_pass http://127.0.0.1:9080/check;
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";
      proxy_set_header X-Original-Host $host;
    }
    location @login {
      if ($machine_request) { return 401; }
      return 302 https://$host/oauth2/start?rd=/;
    }
    location / {
      auth_request /_authn_check;
      auth_request_set $principal $upstream_http_x_cluster_principal;
      auth_request_set $app_cookie $upstream_http_x_upstream_cookie;
      error_page 401 = @login;
      set $backend http://UPSTREAM;
      proxy_pass $backend;
      proxy_request_buffering off;
      proxy_buffering off;
      proxy_read_timeout 300s;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Forwarded-Port 443;
      proxy_set_header X-Cluster-Principal $principal;
      proxy_set_header X-Forwarded-User $principal;
      proxy_set_header X-Auth-Request-User $principal;
      proxy_set_header X-Forwarded-Email "";
      proxy_set_header X-Forwarded-Groups "";
      proxy_set_header X-Forwarded-Preferred-Username "";
      proxy_set_header X-Forwarded-Access-Token "";
      proxy_set_header X-Auth-Request-Email "";
      proxy_set_header X-Auth-Request-Groups "";
      proxy_set_header X-Auth-Request-Access-Token "";
      proxy_set_header Remote-User "";
      proxy_set_header X-Cluster-Token "";
      proxy_set_header X-Original-Host "";
      proxy_set_header Authorization AUTH_HEADER;
      proxy_set_header Cookie $app_cookie;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }
  }
'''.replace("HOST", site["host"]).replace("UPSTREAM", site["upstream"]).replace("AUTH_HEADER", auth_header)
    nginx += "}\n"

    oauth = '''# Generated. 'sub' is used for identity; email addresses grant no privileges.
provider = "oidc"
provider_display_name = "authentik"
client_id = "cluster-sites"
http_address = "127.0.0.1:4180"
reverse_proxy = true
upstreams = ["static://202"]
scope = "openid"
oidc_email_claim = "sub"
oidc_issuer_url = "https://auth.${DOMAIN}/application/o/cluster-sites/"
skip_oidc_discovery = true
login_url = "https://auth.${DOMAIN}/application/o/authorize/"
redeem_url = "https://auth.${DOMAIN}/application/o/token/"
oidc_jwks_url = "https://auth.${DOMAIN}/application/o/cluster-sites/jwks/"
provider_ca_files = ["/ca/ca.crt"]
redirect_url = "/oauth2/callback"
email_domains = ["*"]
cookie_name = "__Host-cluster_sso"
cookie_secure = true
cookie_httponly = true
cookie_samesite = "lax"
cookie_expire = "1h"
cookie_refresh = "0"
cookie_csrf_per_request = true
cookie_csrf_per_request_limit = 8
set_xauthrequest = true
code_challenge_method = "S256"
insecure_oidc_skip_nonce = false
skip_provider_button = true
pass_access_token = false
pass_authorization_header = false
pass_basic_auth = false
request_logging = false
auth_logging = false
silence_ping_logging = true
'''
    oauth += "whitelist_domains = " + json.dumps([s["host"] for s in sites]) + "\n"

    blueprint = '''# Generated. Secret material is resolved from the worker's environment.
version: 1
metadata:
  name: Cluster sites OIDC
entries:
  - model: authentik_providers_oauth2.oauth2provider
    id: cluster-sites-provider
    identifiers:
      name: cluster-sites
    attrs:
      client_id: cluster-sites
      client_secret: !Env OAUTH2_CLIENT_SECRET
      client_type: confidential
      # New authentik providers default to no grants; enable the browser flow.
      grant_types:
        - authorization_code
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
      sub_mode: hashed_user_id
      issuer_mode: per_provider
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [managed, goauthentik.io/providers/oauth2/scope-openid]]
      redirect_uris:
'''
    for site in sites:
        blueprint += f"        - matching_mode: strict\n          url: https://{site['host']}/oauth2/callback\n"
    blueprint += '''  - model: authentik_core.application
    identifiers:
      slug: cluster-sites
    attrs:
      name: Cluster sites
      provider: !KeyOf cluster-sites-provider
      meta_launch_url: https://home.${DOMAIN}
'''
    return {
        "apps/edge/nginx.conf": nginx,
        "apps/edge/oauth2-proxy.cfg": oauth,
        "apps/edge/sites.json": json.dumps({s["host"]: s for s in sites}, indent=2) + "\n",
        "apps/authentik/cluster-sites.yaml": blueprint,
        "infrastructure/routes/routes.yaml": yaml.safe_dump_all(routes, sort_keys=False),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    failed = []
    for name, content in generate().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                failed.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if failed:
        sys.exit("Regenerate with python3 scripts/generate.py: " + ", ".join(failed))


if __name__ == "__main__":
    main()
